[project]
name = "MCP-Server"
version = "0.0.1"
description = "MCP server"
authors = [
    { name = "Sandeep Patra", email = "sandeep@platformance.io" },
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aws-cdk-lib",
]